# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and set up backend
      run: |
        cd backend
        npm ci
        touch .env
        echo "${{ secrets.PROD_BACKEND_ENV }}" > .env
        pm2 stop --silent some-name
        pm2 delete --silent some-name
        pm2 start "npm run start" --name backend

    - name: Build and set up frontend
      run: |
        cd frontend
        npm ci
        touch .env.production
        echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env.production
        npm run build
